#Stage 1: Build web app
FROM node:alpine as webapp

WORKDIR /usr/src/app

COPY . ./

RUN yarn
RUN yarn build


# Stage 2 - Add NGNIX on the top of it
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=webapp /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

WORKDIR /usr/share/nginx/html
COPY ./env.sh .
COPY ./.env .env

RUN apk add --no-cache bash

RUN chmod +x env.sh

CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]
