#Stage 1: Build web app
FROM node:alpine as webapp

WORKDIR /usr/src/app

COPY . ./

RUN npm install --production
RUN npm run build


# Stage 2 - Add NGNIX on the top of it
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=webapp /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

WORKDIR /usr/share/nginx/html

RUN apk add --no-cache bash

CMD ["/bin/bash", "-c", "nginx -g \"daemon off;\""]
